/*
 *  ======== config.c ========
 *  Configuration-specific definitions
 *
 *  DO NOT EDIT - This file is generated by the SysConfig tool for
 *  the TI Sensors in this application.
 */
#include <stdint.h>

#include "TMP1075.h"

#include "config.h"

/*
 *  ======== TMP1075_0 ========
 *  TMP1075 Sensor configuration settings
 */
static TMP1075_State TMP1075_0_state = {
    .config = (TMP1075_CONFIG_OS_DISABLE | \
               TMP1075_CONFIG_CR_37HZ | \
               TMP1075_CONFIG_FQ_1FAULT | \
               TMP1075_CONFIG_POL_LOW | \
               TMP1075_CONFIG_TM_COMP | \
               TMP1075_CONFIG_SD_SD),
    .tlow = 0x2000U,//0x4B00U, /* Temperature Low is 75 Celsius */
    .thigh = 0x2400U,//0x5000U, /* Temperature High is 80 Celsius */


    /* Sensor's I2C bus ID and address */
    .busId   = 0x48U,
    .devAddr = 0x00U,

    /* one-shot delay time (ms) */
    .osWait  = 35
};
const TMP1075_Handle TMP1075_0 = &TMP1075_0_state;

