/*
 *  ======== TMP1075.c ========
 *  TMP1075 APIs for initialization and use of the TMP1075 peripheral
 *
 *  DO NOT EDIT - This file is generated by the SysConfig tool for
 *  the TI Sensors in this application.
 */

#include <stddef.h>
#include <stdint.h>

#include "TMP1075.h"
#include <ti/drivers/I2C.h>
#include<ti/display/Display.h>
#include "unistd.h"

#define MSB(u16) (((u16) & 0xFF00U) >> 8)
#define LSB(u16) ((u16) & 0xFFU)
extern Display_Handle display1;
extern I2C_Handle i2c;
extern I2C_Transaction i2cTransaction;
/*
 *  ======== writeReg ========
 */
uint8_t writeReg(TMP1075_Handle sensor, uint8_t regAddr, uint16_t value)
{
    unsigned char writeBuffer[3],slave_add;
    slave_add=sensor->busId;
    //writeBuffer[0] = sensor->devAddr; // MSB
    writeBuffer[0] = regAddr;
    writeBuffer[1] = (uint8_t)MSB(value);
    writeBuffer[2] = (uint8_t)LSB(value);
        I2C_Transaction i2cTransaction;
        i2cTransaction.slaveAddress = slave_add; // 7-bit address
        i2cTransaction.writeBuf = writeBuffer;
        i2cTransaction.writeCount = 3;
        i2cTransaction.readBuf = NULL;
        i2cTransaction.readCount = 0;

        if (!I2C_transfer(i2c, &i2cTransaction)) {
            // Handle I2C transfer error
            return 0;
        }
        return 1;
  //  mcu_i2cTransfer(sensor->busId, sensor->devAddr, txBuf, 3, NULL, 0);
}

/*
 *  ======== TMP1075_config ========
 * Configure device with current settings.
 */
void TMP1075_config(TMP1075_Handle sensor)
{
    /* Initialize the bus containing this sensor */
 //   mcu_i2cInit(sensor->busId);

    /* Write sensor Configuration Register */

    writeReg(sensor, TMP1075_CONFIG, sensor->config);

    /* Write sensor Temperature High and Low Registers */

   writeReg(sensor, TMP1075_TLOW, sensor->tlow);
    writeReg(sensor, TMP1075_THIGH, sensor->thigh);


}

/*
 *  ======== TMP1075_read ========
 *  Read temperature register
 */
int32_t TMP1075_read(TMP1075_Handle sensor)
{

    uint8_t rxBuf[2] = {0};
    int32_t tmp;

    /* If needed, setup one shot measurement */
    if (sensor->config & TMP1075_CONFIG_SD_SD) {
        /* Reset one shot enable */
        writeReg(sensor, TMP1075_CONFIG, sensor->config | TMP1075_CONFIG_OS_ENABLE);

        /* Wait for conversion to complete */
     //   mcu_msWait(sensor->osWait);
        usleep(35000);
    }

    /* Read temperature register */
    
      unsigned char writeBuffer[1];

       writeBuffer[0]=sensor->devAddr;
      // writeBuffer[1]= TMP1075_TEMP;
       I2C_Transaction i2cTransaction;
        i2cTransaction.slaveAddress = sensor->busId; // 7-bit address
        i2cTransaction.writeBuf = writeBuffer;
        i2cTransaction.writeCount = 1;
        i2cTransaction.readBuf = rxBuf;
        i2cTransaction.readCount = 2;

        if (!I2C_transfer(i2c, &i2cTransaction)) {
            // Handle I2C transfer error
            return;
        }
   // mcu_i2cTransfer(sensor->busId, sensor->devAddr, txBuf, 1, rxBuf, 2);

    /* Sign extend and combine MSB with LSB */
    tmp = (((int32_t)(int8_t)rxBuf[0]) << 8) | rxBuf[1];

    return (tmp);
}


/*
 *  ======== TMP1075_toIntCelsius ========
 *  Convert raw temperature register value to degrees Celsius rounded to the
 *  nearest integer
 */
int32_t TMP1075_toIntCelsius(int32_t x)
{
    /* Shift raw register value to form a proper Q4 value */
    x >>= 4;

    /* Optional: Add bias to round before the final truncation */
    x += (x >= 0) ? (1 << 3) : -(1 << 3);

    /* Convert Q4 value to whole number */
    x /= 1 << 4; /* use division so small negative values round to 0 */

    return x;
}

/*
 *  ======== TMP1075_toMilliCelsius ========
 *  Convert raw temperature register value to milli-degrees Celsius
 */
int32_t TMP1075_toMilliCelsius(int32_t x)
{
    /* Shift raw register value to form a proper Q4 value */
    x >>= 4;

    /* Scale to milli-degrees, convert Q4 value to a whole number */
    return ((1000 * x) >> 4);
}

/*
 *  ======== TMP1075_toFloatCelsius ========
 *  Convert raw temperature register value to degrees Celsius
 */
float TMP1075_toFloatCelsius(int32_t x)
{
    /* Shift raw register value to form a proper Q4 value */
    x >>= 4;

    /* Convert Q4 value to a float */
    return ((float)x * 0.0625f);
}
